### PR TITLE
need this for kale

### PR DESCRIPTION
**Pull request by erikmingo**

### CODE REVIEW

**Comment by erikmingo** [comment]
@kapost/insights pretty simple change, need this so we can delete segments.

**Comment by derekclee** [comment]
:+1:

**Comment by bwebster** [comment]
@erikmingo you mentioned something about the delete only being available in the 2.0 api.  Is that related to this change?

**Comment by erikmingo** [comment]
@bwebster we actually don't have to use the newer version to use delete i was just confused.
This PR just adds a method, so we can delete segments.

**Pull request merged**
